obstacles:
  observation_sources: base_scan base_cloud
  base_scan:
    data_type: LaserScan
    topic: base_scan
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.1
    max_obstacle_height: 0.3
  base_cloud:
    data_type: PointCloud2
    topic: head_camera/depth_downsample/points
    min_obstacle_height: 0.1
    max_obstacle_height: 0.4
    marking: true
    clearing: true
  z_voxels: 8
  z_resolution: 0.25
  max_obstacle_height: 2.0
